### ISSUE TITLE
Meeting: 11 September 2023 -- TPAC 2023

### ISSUE THREAD

**Issue by seanturner** [patcg/admin#16]
The Private Advertising Technology Community Group will be meeting at [TPAC 2023](https://www.w3.org/2023/09/TPAC/) in a hybrid format, the W3C supports both in-person and remote attendees, on September 11th. Two sessions have been [scheduled](https://www.w3.org/2023/09/TPAC/schedule.html#monday). The 1st session is 1.5 hours and starts at 0930 (09:30am) and 2nd session is two hours and starts at 1430 (02:30pm); both times are Seville Time (UTC+2). A repo for [this meeting](https://github.com/patcg/meetings/tree/main/2023/09/11-tpac) has been created where the agenda, presentations, and minutes will be published. The agenda is being developed now in the [meetings repo](https://github.com/patcg/meetings/issues). The [patcg meeting calendar](https://www.w3.org/groups/cg/patcg/calendar) has been updated to reflect these meeting times.  If you plan to participate, more information about registering can be found [here](https://www.w3.org/2023/09/TPAC/registration.html#fees).

**Comment by bmayd** [comment]
@seanturner The note above says:
> 2nd session is two hours and starts at 1330 (01:30pm) 

This [September 2023 TPAC Meeting page](https://github.com/patcg/meetings/tree/main/2023/09/11-tpac) has the second session at:
> 14:30 (02:30 PM) | 11 Mon | Seville

W3C Calendar has the meeting time at:
> 11 September 2023, 14:30–16:30 Central European Summer Time

Assume what's above is off.

**Comment by seanturner** [comment]
It is; I manage to get one date/time wrong per meeting. Thanks for catching this.
