### ISSUE TITLE
Meeting cadence

### ISSUE THREAD

**Issue by martinthomson** [patcg/admin#2]
During our inaugural meeting at TPAC, several people noted that a weekly schedule with short meetings (1h) might not be optimal for the sort of work that we do.

We need to find a cadence that best suits the sort of work that we are doing.  I suggest that 6 weeks between meetings, with each meeting being of significant duration, might be best for this group.  The work that we are doing is going to be quite involved and longer meetings will allow for deeper discussion about some of the details.

From my perspective, this is even better if we can meet in person.  For that, meeting over 1-3 days can be a good use of time.  That might not be something we can do in the short term, but we should consider that option as it becomes more feasible.  In the interim, conference calls probably need to be quite a bit shorter as they are much harder on people, particularly if they end up being at odd hours.

**Comment by darobin** [comment]
With the minor caveat that I hope we won't be doing in-person meetings every six weeks, I agree.

**Comment by michaelkleber** [comment]
I strongly support for Martin's model of occasional (every 3 months?) multi-day in-person meetings, once "in-person" is feasible, and something approximating that model until then.

I promise this is not _primarily_ motivated by my hope for trips to Australia or Singapore.

**Comment by martinthomson** [comment]
I certainly hope that we don't meet in person that often.

However, if we are going to do something this big and tricky in any reasonable time frame, I suspect that a few meetings a year will be necessary. I have observed that the speed at which agreement on difficult questions is reached during the pandemic has slowed. A lot. Something this big could take a decade at that place.

**Comment by seanturner** [comment]
Going to close this issue because there is now a meeting cadence and timing issue in [patcg/meetings](https://github.com/patcg/meetings/issues/4).
