### ISSUE TITLE
Meeting: 21st & 23rd June 2022

### ISSUE THREAD

**Issue by seanturner** [patcg/admin#7]
The Private Advertising Technology CG is having a meeting on June 21st and 23rd.  The meeting will start at [0800 CEST / 0700 BST / 0600 UTC / 0200 EDT / 2300 PDT (previous day) / 1400 Singapore / 1600 AEST](https://everytimezone.com/?t=62afb880,708). The duration will be 3 hours each day. A repo for [this meeting](https://github.com/patcg/meetings/tree/main/2022/06/21-telecon) has been created where the agenda, presentations, minutes, etc. will be published. The agenda is being developed now in the [meetings repo](https://github.com/patcg/meetings/issues). The [patcg meeting calendar](https://www.w3.org/groups/cg/patcg/calendar) has also been updated to reflect meeting time. The Zoom details are available via the [patcg meeting calendar](https://www.w3.org/groups/cg/patcg/calendar) and [this meeting's repo](https://github.com/patcg/meetings/tree/main/2022/06/21-telecon).

See you there!

**Comment by AramZS** [comment]
Updated Repo link to latest - https://github.com/patcg/meetings/tree/main/2022/06/21-telecon

**Comment by seanturner** [comment]
Thanks again for another successful meeting.
