### ISSUE TITLE
Meeting: 9th & 11th August 2022

### ISSUE THREAD

**Issue by seanturner** [patcg/admin#8]
The Private Advertising Technology CG is having a meeting on August 9th and 11th.  The meeting will start at [2400 CET / 2300BST / 2200 UTC / 1800 EST / 1500 PST / 0600 Singapore (next day) / 0800 AEST (next day)](https://everytimezone.com/?t=62e71780,ac8). The duration will be 3 hours each day. A repo for [this meeting](https://github.com/patcg/meetings/tree/main/2022/08/09-telecon) has been created where the agenda, presentations, minutes, etc. will be published. The agenda is being developed now in the [meetings repo](https://github.com/patcg/meetings/issues). The [patcg meeting calendar](https://www.w3.org/groups/cg/patcg/calendar) has also been updated to reflect meeting time. The Zoom details are available via the [patcg meeting calendar](https://www.w3.org/groups/cg/patcg/calendar) and [this meeting's repo](https://github.com/patcg/meetings/tree/main/2022/08/09-telecon).

See you there!

**Comment by bmayd** [comment]
@seanturner You have the June dates identified in the body of your post.

**Comment by seanturner** [comment]
@bmayd Thanks!
